/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_bingoogol_ndk_jni_HelloInt */

#ifndef _Included_cn_bingoogol_ndk_jni_HelloInt
#define _Included_cn_bingoogol_ndk_jni_HelloInt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_bingoogol_ndk_jni_HelloInt
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_bingoogol_ndk_jni_HelloInt_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
