/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_bingoogol_ndk_jni_CInvokeJava */

#ifndef _Included_cn_bingoogol_ndk_jni_CInvokeJava
#define _Included_cn_bingoogol_ndk_jni_CInvokeJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_bingoogol_ndk_jni_CInvokeJava
 * Method:    callHelloFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_bingoogol_ndk_jni_CInvokeJava_callHelloFromJava
  (JNIEnv *, jobject);

/*
 * Class:     cn_bingoogol_ndk_jni_CInvokeJava
 * Method:    callAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_bingoogol_ndk_jni_CInvokeJava_callAdd
  (JNIEnv *, jobject);

/*
 * Class:     cn_bingoogol_ndk_jni_CInvokeJava
 * Method:    callPrintStaticString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_bingoogol_ndk_jni_CInvokeJava_callPrintStaticString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
