/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_bingoogol_ndk_ui_activity_MainActivity */

#ifndef _Included_cn_bingoogol_ndk_ui_activity_MainActivity
#define _Included_cn_bingoogol_ndk_ui_activity_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_bingoogol_ndk_ui_activity_MainActivity
 * Method:    callCInvokeJavaPrintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_bingoogol_ndk_ui_activity_MainActivity_callCInvokeJavaPrintString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
