/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_bingoogol_ndk_jni_HelloString */

#ifndef _Included_cn_bingoogol_ndk_jni_HelloString
#define _Included_cn_bingoogol_ndk_jni_HelloString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_bingoogol_ndk_jni_HelloString
 * Method:    getFullName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_bingoogol_ndk_jni_HelloString_getFullName
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     cn_bingoogol_ndk_jni_HelloString
 * Method:    getCString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_bingoogol_ndk_jni_HelloString_getCString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
