/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_bingoogol_ndk_jni_JavaInvokeC */

#ifndef _Included_cn_bingoogol_ndk_jni_JavaInvokeC
#define _Included_cn_bingoogol_ndk_jni_JavaInvokeC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_bingoogol_ndk_jni_JavaInvokeC
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cn_bingoogol_ndk_jni_JavaInvokeC_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cn_bingoogol_ndk_jni_JavaInvokeC
 * Method:    getFullName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_bingoogol_ndk_jni_JavaInvokeC_getFullName
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
