/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bingoogol_jni02_engine_JNIProvider */

#ifndef _Included_com_bingoogol_jni02_engine_JNIProvider
#define _Included_com_bingoogol_jni02_engine_JNIProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bingoogol_jni02_engine_JNIProvider
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bingoogol_jni02_engine_JNIProvider_helloFromC
  (JNIEnv *, jobject);

/*
 * Class:     com_bingoogol_jni02_engine_JNIProvider
 * Method:    hello_from_c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bingoogol_jni02_engine_JNIProvider_hello_1from_1c
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
