/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bingoogol_jni04_engine_DataProvider */

#ifndef _Included_com_bingoogol_jni04_engine_DataProvider
#define _Included_com_bingoogol_jni04_engine_DataProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bingoogol_jni04_engine_DataProvider
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_bingoogol_jni04_engine_DataProvider_sub
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_bingoogol_jni04_engine_DataProvider
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_bingoogol_jni04_engine_DataProvider_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_bingoogol_jni04_engine_DataProvider
 * Method:    sayHelloInc
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bingoogol_jni04_engine_DataProvider_sayHelloInc
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bingoogol_jni04_engine_DataProvider
 * Method:    intMethod
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_bingoogol_jni04_engine_DataProvider_intMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
